apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.nameSpace }}
  name: jke-role-binding
  labels:
    app: jke-role-binding
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jke-cluster-role
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Values.nameSpace }}
  apiGroup: rbac.authorization.k8s.io