apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.nameSpace }}
  name: {{ template "jke.bankstreet.fullname" . }}
  labels:
    app: {{ template "jke.bankstreet.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "jke.bankstreet.name" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ template "jke.bankstreet.name" . }}
        release: {{ .Release.Name }}
        tier: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository}}/{{ .Values.nameSpace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http-server
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 40
          #   timeoutSeconds: 2
          #   periodSeconds: 3
          #   failureThreshold: 2
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 100
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   failureThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 40
          #   timeoutSeconds: 2
          #   periodSeconds: 3
          #   failureThreshold: 2
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 100
          #   timeoutSeconds: 2
          #   periodSeconds: 8
          #   failureThreshold: 1                            
          env:
            - name: GET_HOSTS_FROM
              value: dns
            # General
            - name: server.port
              valueFrom:
                configMapKeyRef:
                  name: jke-configmap
                  key: server.port.bankstreet
            # JKE API Service URL
            - name: jke.api.service.url.all
              valueFrom:
                configMapKeyRef:
                  name: jke-configmap
                  key: jke.api.service.url.all
            - name: jke.api.service.url.fd
              valueFrom:
                configMapKeyRef:
                  name: jke-configmap
                  key: jke.api.service.url.fd
            - name: jke.api.service.url.rd
              valueFrom:
                configMapKeyRef:
                  name: jke-configmap
                  key: jke.api.service.url.rd                                    