apiVersion: v1
kind: Service
metadata:
  name: <PROJECT>-api
  # namespace: <PROJECT>
  labels:
    app: <PROJECT>-api
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30033
      port: 80
      targetPort: 8085
  selector:
    app: <PROJECT>-api

# Note : Springboot apps runs in 8085
