apiVersion: v1
kind: Service
metadata:
  name: jke-web
  namespace: hclapp
  labels:
    app: jke-web
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30031
      port: 80
      targetPort: 8045
  selector:
    app: jke-web

# Note : Springboot apps runs in 8045
