apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jke-role-binding
  namespace: {{ .Values.nameSpace }}
  labels:
    app: jke-role-binding
    name: jke-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jke-cluster-role
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Values.nameSpace }}
  apiGroup: rbac.authorization.k8s.io