apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.nameSpaceChannel }}
  name: jke-image-pull-secret
  labels:
    app: jke-image-pull-secret
    name: jke-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerImagePullSecretValue }}

####  Generate dockerconfigjson using the below command
# Here namespace and myname are not used during the encryption
# kubectl create secret docker-registry myname --docker-server=mycluster.icp:8500 --docker-username=admin --docker-password=admiiinnnn --docker-email=null  --dry-run -o yaml
# kubectl create secret docker-registry myname --docker-server=hubcluster.icp:8500 --docker-username=admin --docker-password=admin --docker-email=null  --dry-run -o yaml