---
# Source: jke-prerequisite/templates/role-binding-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jke-role-binding
  namespace: jke-app
  labels:
    app: jke-role-binding
    name: jke-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jke-cluster-role
subjects:
- kind: Group
  name: system:serviceaccounts:jke-app
  apiGroup: rbac.authorization.k8s.io