---
# Source: jke-application/templates/21-deployable-web.yaml
apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  namespace: jke-app
  name: jke-deployable-deployment-web
  labels:
    app: jke-application
    servicekind: ApplicationService
spec:
  deployer:
    kind: Deployment
    kube:
      namespace: jke-app
      template:
        metadata:
          name: jke-web
        spec:
          selector:
            matchLabels:
              app: jke-application
              release: release-name
              subname: web
          replicas: 1
          template:
            metadata:
              labels:
                app: jke-application
                release: release-name
                subname: web
            spec:
              containers:
                - name: jke-application
                  image: "gandigit/jke-web:latest"
                  imagePullPolicy: Always
                  ports:
                    - name: http
                      containerPort: 9030
                      protocol: TCP
                    - name: https
                      containerPort: 8082
                  env:
                  - name: GET_HOSTS_FROM
                    value: dns
                  # API URLs
                  - name: jke.service.url.interest.all
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: jke.service.url.interest.all
                  - name: jke.service.url.stock.all
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: jke.service.url.stock.all
                  # DB2 Database
                  - name: spring.dbprob.hostname
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: spring.dbprob.hostname
                  - name: spring.dbprob.port
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: spring.dbprob.port
                  - name: spring.dbprob.dbname
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: spring.dbprob.dbname
                  - name: spring.datasource.url
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: spring.datasource.url
                  - name: spring.datasource.username
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: spring.datasource.username
                  - name: spring.datasource.password
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: spring.datasource.password
                  # MQ
                  - name: ibm.mq.queueManager
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: ibm.mq.queueManager
                  - name: ibm.mq.channel
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: ibm.mq.channel
                  - name: ibm.mq.connName
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: ibm.mq.connName
                  - name: ibm.mq.queueName.req
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: ibm.mq.queueName.req
                  - name: ibm.mq.queueName.int
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: ibm.mq.queueName.int
                  - name: ibm.mq.queueName.res
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: ibm.mq.queueName.res
                  - name: jke.mq.ace.enabled
                    valueFrom:
                      configMapKeyRef:
                        name: jke-config-map
                        key: jke.mq.ace.enabled 
              imagePullSecrets:
                - name: jke-prerequisite-icp-ocp-image-pull-secret
---
apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: jke-deployable-service-web
  labels:
    app: jke-application
    name: jke-deployable-service-web
    servicekind: ApplicationService
spec:
  deployer:
    kind: Service
    kube:
      namespace: jke-app
      template:
        metadata:
          name: jke-web
          labels:
            app: jke-application
          annotations:
            prometheus.io/scrape: 'true' 
            prometheus.io/port: '9030'
            prometheus.io/path: '/actuator/prometheus'
            mcm.ibm.com/service-discovery: "{}"            
        spec:
          type: NodePort
          ports:
            - name: my-http
              port: 9030
              targetPort: 9030
              nodePort: 31330
          selector:
            app: jke-application
            release: release-name
            subname: web