---
# Source: jke-application/templates/35-application-relationship-bankstreet.yaml
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  namespace: jke-app
  name: jke-deployment-bankstreet
  labels:
    app: jke-application
    name: jke-deployment-bankstreet
spec:
  type: contains
  destination:
    kind: Deployable
    name: jke-deployable-deployment-bankstreet
  source:
    kind: Application
    name: jke-application
---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  namespace: jke-app
  name: jke-service-bankstreet
  labels:
    app: jke-application
    name: jke-service-bankstreet
spec:
  type: contains
  destination:
    kind: Deployable
    name: jke-deployable-service-bankstreet
  source:
    kind: Application
    name: jke-application
---
