replicaCount: 2

appInClusterNamespace: hcl-app

targetCluster:
  labelSelector:
    matchLabelsBothClusters:
      environment: Prod
      # datacenter: london
      # name: cluster-3
      purpose: app
    matchLabelsCluster2:
      environment: Prod
      name: cluster-2
      purpose: app
    matchLabelsCluster3:
      environment: Prod
      name: cluster-3
      purpose: app
  resourceSelector:
    type: cpu
  compliances: ""