apiVersion: v1
kind: Service
metadata:
  name: <PROJECT>-web
  # namespace: <PROJECT>
  labels:
    app: <PROJECT>-web
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30031
      port: 80
      targetPort: 8085
  selector:
    app: <PROJECT>-web

# Note : Springboot apps runs in 8085
