apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.dockerImagePullSecretName }}
  # namespace: {{ .Values.nameSpace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJnYW5kaWdpdCIsInBhc3N3b3JkIjoiaWJtUGFzczAiLCJlbWFpbCI6ImdhbmRoaTU1NUBnbWFpbC5jb20iLCJhdXRoIjoiWjJGdVpHbG5hWFE2YVdKdFVHRnpjekE9In19fQ==
