apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectNameWeb }}
  # namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.projectNameWeb }}
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: {{ .Values.nodePortWeb }}
      port: 80
      targetPort: 8045
  selector:
    app: {{ .Values.projectNameWeb }}

# Note : Springboot apps runs in 8045